version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8086:81

  descriptions:
    depends_on:
      - mysqldb
    build: backend/descriptions
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "create",
        "spring.jpa.defer-datasource-initialization":"true",
        "spring.sql.init.mode" : "always" ,
        "spring.datasource.initialization-mode" : "always"
        }'
    stdin_open: true
    tty: true
  ratings:
    build: backend/ratings
    ports:
      - 8080:8080
  price:
    build: backend/price
    ports:
      - 8081:8081
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 80:80
  gateway:
    build: backend/gateway
    container_name: gateway
    hostname: qub
    ports:
      - 8085:8085

volumes:
  db:
